---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: 'files/patch-*'
      - id: trailing-whitespace
        exclude: 'files/patch-*'
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: check-case-conflict
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
        args: [-I, .codespellignore]
        exclude: >
          (?x)^(
            templates/workstation.inf|
            defaults/main.yml|
            vars/de-DE.yml
          )$
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v25.12.0
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
#  - repo: https://github.com/Yelp/detect-secrets
#    rev: v1.1.0
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
#        exclude: .*/tests/.*
