---
dist: trusty
language: python
python: "2.7"
before_install:
 - ln -s ansible-harden-windows ../juju4.harden-windows
install:
  - sudo apt-get install libxml2-utils
  - pip install ansible ansible-lint
  - ansible --version
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"
  - "echo \"[test-kitchen]\nlocalhost\" > inventory"
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"

script:
  - "ansible-lint tasks/main.yml"

# Check the role/playbook's syntax.
  - "ansible-playbook -i inventory --syntax-check test/integration/default/default.yml"
