---
## Adobe Reader Protected mode
## FIXME! not idempotent

- name: Win | FeatureLockDown Acrobat reader
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\FeatureLockDown
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bProtectedMode, data: 1 }
    - { value: iProtectedView, data: 2 }
    - { value: bEnhancedSecurityStandalone, data: 1 }
    - { value: bEnhancedSecurityInBrowser, data: 1 }
    - { value: bDisableOSTrustedSites, data: 1 }
    - { value: bDisableTrustedFolders, data: 1 }
    - { value: bDisableTrustedSites, data: 1 }
    - { value: bEnableCertificateBasedTrust, data: 0 }
    - { value: iFileAttachmentPerms, data: 0 }
    - { value: bDisableJavaScript, data: 1 }
    - { value: bCommercialPDF, data: 1 }
    - { value: bRegisterProduct, data: 1 }
    - { value: bShowAdsAllow, data: 1 }
    - { value: bPurchaseAcro, data: 1 }
    - { value: bShowEbookMenu, data: 1 }
    - { value: bUsageMeasurement, data: 1 }
    - { value: bDisablePDFHandlerSwitching, data: 1 }
    - { value: bEnableFlash, data: 0 }
    - { value: bEnable3D, data: 0 }

- name: FeatureLockDown Acrobat reader - 64bits
  win_regedit:
    key: HKLM:\SOFTWARE\Wow6432Node\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\FeatureLockDown
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bProtectedMode, data: 1 }
    - { value: iProtectedView, data: 2 }
    - { value: bEnhancedSecurityStandalone, data: 1 }
    - { value: bEnhancedSecurityInBrowser, data: 1 }
    - { value: bDisableOSTrustedSites, data: 1 }
    - { value: bDisableTrustedFolders, data: 1 }
    - { value: bDisableTrustedSites, data: 1 }
    - { value: bEnableCertificateBasedTrust, data: 0 }
    - { value: iFileAttachmentPerms, data: 0 }
    - { value: bDisableJavaScript, data: 1 }
    - { value: bCommercialPDF, data: 1 }
    - { value: bRegisterProduct, data: 1 }
    - { value: bShowAdsAllow, data: 1 }
    - { value: bPurchaseAcro, data: 1 }
    - { value: bShowEbookMenu, data: 1 }
    - { value: bUsageMeasurement, data: 1 }
    - { value: bDisablePDFHandlerSwitching, data: 1 }
    - { value: bEnableFlash, data: 0 }
    - { value: bEnable3D, data: 0 }

- name: Acrobat reader - cDefaultLaunchAttachmentPerms
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\FeatureLockDown\cDefaultLaunchAttachmentPerms
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: "{{ item.datatype }}"
  with_items:
    - { value: iUnlistedAttachmentTypePerm, data: 3, datatype: dword }
    - { value: "tBuiltInPermList", data: "version:1|.docx:2|.xls:2|.exe:3|.hs:3", datatype: string }

- name: Acrobat reader - TrustManager
  win_regedit:
    key: HKCU:\Software\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\TrustManager
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bDisableTemporaryFileProtectedView, data: 0 }
## For Outlook Office 2010+
    - { value: bEnableAlwaysOutlookAttachmentProtectedView, data: 0 }

- name: Acrobat reader - Workflows
  win_regedit:
    key: HKCU:\Software\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\Workflows
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bEnableAcrobatHS, data: 0 }
    - { value: bEnableRTCPart, data: 0 }
    - { value: bEnableRTCAuth, data: 0 }
    - { value: bEnableShareFile, data: 0 }
    - { value: bEnableDocCtrInit, data: 0 }

- name: Acrobat reader - cCloud
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\cCloud
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bDisableADCFileStore, data: 1 }

- name: Acrobat reader - cServices
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\cServices
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bEnableSignPane, data: 1 }

- name: Acrobat reader - cWebmailProfiles
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\cWebmailProfiles
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: dword
  with_items:
    - { value: bDisableWebmail, data: 1 }

## Logging ?
## https://www.adobe.com/devnet-docs/acrobatetk/tools/AppSec/protectedmode.html
- name: Acrobat reader - Privileged
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Adobe\Acrobat Reader\{{ harden_win_adobereader_v }}\Privileged
    value: "{{ item.value }}"
    data: "{{ item.data }}"
    datatype: string
  with_items:
    - { value: tBrokerLogfilePath, data: 'c:\temp\BrokerLogfile.log' }
