---

- name: check if mbrfilter archive is present
  win_stat: path="{{ harden_win_temp_dir }}\\{{ harden_win_mbrfilter_url | basename }}"
  register: mbrfilterdl
- name: Download mbrfilter
  win_get_url:
    url: "{{ harden_win_mbrfilter_url }}"
    dest: "{{ harden_win_temp_dir }}\\{{ harden_win_mbrfilter_url | basename }}"
## FIXME! no checksum option, https://github.com/ansible/ansible-modules-core/issues/4901
  when: not mbrfilterdl.stat.exists

- name: Uncompress mbrfilter
  win_unzip:
    src: "{{ harden_win_temp_dir }}\\{{ harden_win_mbrfilter_url | basename }}"
    dest: "{{ harden_win_temp_dir }}\\mbrfilter"
    creates: "{{ harden_win_temp_dir }}\\mbrfilter\\64\\mbrfilter.sys"

- name: Install mbrfilter driver
  win_command: >
    RUNDLL32.EXE SETUPAPI.DLL,InstallHinfSection DefaultInstall 132
        {{ harden_win_temp_dir }}\\mbrfilter\\64\\mbrfilter.sys

- debug: msg="WARNING! Talos Mbrfilter - You will need to reboot for driver to be effective."
