---

- name: Ensure user _monitorsec is present
  win_user:
    name: _monitorsec
    password: "{{ ansible_become_password }}"
    state: present
    groups:
      - Users
  ignore_errors: true

# FIXME! user must have 'Log on as a batch job' right
# Computer Configuration\Windows Settings\Security Settings\Local Policies\User Rights Assignment
# if know SID beforehand, can be through secedit. else needs win2k3 support kit
- name: Download win2k3 support kit for ntrights
  get_url:
    url: https://download.microsoft.com/download/8/e/c/8ec3a7d8-05b4-440a-a71e-ca3ee25fe057/rktools.exe
    dest: "{{ harden_win_temp_dir }}\\rktools.exe"
#  win_command: ntrights.exe -u _monitorsec +r SeBatchLogonRight

# No checksums options
- name: Monitor | download tools
  win_get_url:
    url: "{{ item.u }}"
    dest: "{{ harden_win_temp_dir }}\\{{ item.u | basename }}"
  with_items: "{{ harden_win_monitorsec_tools }}"

- name: Monitor | unarchive tools
  win_unzip:
    src: "{{ harden_win_temp_dir }}\\{{ item.u | basename }}"
    dest: "{{ harden_win_temp_dir }}\\{{ item.u | basename | regexp_replace('.zip$', '') }}"
#    creates: "{{ harden_win_temp_dir }}\\{{ item.u | basename | regexp_replace('.zip$', '') }}\\{{ item.c }}"
  with_items: "{{ harden_win_monitorsec_tools }}"

- name: Monitor | Ensure inspec is present
  win_chocolatey:
    name: inspec
    state: present

- name: Monitor daily run | Inspec windows-baseline
  win_command: "c:\\opscode\\inspec\\bin\\inspec.bat exec https://github.com/juju4/windows-baseline >{{ harden_win_log_dir }}\\inspec.log"
  ignore_errors: true

- name: Monitor daily run | Inspec
  win_scheduled_task:
    name: Daily-Security-Monitoring-Inspec
    description: Win state check
    executable: "c:\\opscode\\inspec\\bin\\inspec.bat"
    arguments: "exec https://github.com/juju4/windows-baseline --format=json >{{ harden_win_log_dir }}\\inspec.log"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ harden_win_domain }}\\_monitorsec"
    password: "{{ ansible_become_password }}"
#    runlevel: highest

- name: Monitor daily run | PingCastle
  win_scheduled_task:
    name: Daily-Security-Monitoring-PingCastle
    description: AD state check
    executable: "{{ harden_win_temp_dir }}\\PingCastle\\PingCastle.exe"
    arguments: "--healthcheck --server \"{{ harden_win_domain }}\" --log"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ harden_win_domain }}\\_monitorsec"
    password: "{{ ansible_become_password }}"
#    runlevel: highest

- name: Monitor daily run | BloodHound-Sharphound
  win_scheduled_task:
    name: Daily-Security-Monitoring-Sharphound
    description: AD state check
    executable: "{{ harden_win_temp_dir }}\\Bloodhound\\resources\\apps\\ingestors\\SharpHound.exe"
    time: 6am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ harden_win_domain }}\\_monitorsec"
    password: "{{ ansible_become_password }}"
#    runlevel: highest

# https://github.com/l0ss/Grouper
- name: Monitor daily run | Get-GPOReport
  win_scheduled_task:
    name: Daily-Security-Monitoring-Get-GPOReport
    description: AD state check
    executable: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
    arguments: "-ExecutionPolicy Unrestricted -NonInteractive -Command 'Get-GPOReport -All -ReportType xml -Path {{ harden_win_temp_dir }}\\gporeport.xml'"
    time: 4am
    frequency: daily
    state: present
    enabled: yes
    user: "{{ harden_win_domain }}\\_monitorsec"
    password: "{{ ansible_become_password }}"
#    runlevel: highest
