---

- name: try to use trivial passwords
  win_command: "net user _test {{ item }}"
  with_items:
    - passwd
    - 123123123
    - iloveyou
    - dragon123456
  ignore_errors: true
  register: opftest
  failed_when: "'The command completed successfully.' in opftest.stdout"
