---
# https://blogs.technet.microsoft.com/askpfeplat/2013/07/14/why-you-shouldnt-disable-the-task-scheduler-service-in-windows-7-and-windows-8/
# https://support.microsoft.com/en-us/help/305612/how-to-prevent-a-user-from-running-task-scheduler-in-windows

# eventually, allow creation at provisioning and just execution after
- name: TaskScheduler | Disable DragAndDrop, TaskCreation, TaskDeletion globally
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Task Scheduler5.0
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: dword
  with_items:
    - { v: DragAndDrop, d: "{{ harden_win_disable_taskscheduler | ternary(1, 0) }}" }
    - { v: 'Task Creation', d: "{{ harden_win_disable_taskscheduler | ternary(1, 0) }}" }
    - { v: 'Task Deletion', d: "{{ harden_win_disable_taskscheduler | ternary(1, 0) }}" }

- name: TaskScheduler | Disable execution globally
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Microsoft\Windows\Task Scheduler5.0
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: dword
  with_items:
    - { v: Execution, d: "{{ harden_win_disable_taskscheduler_execution | ternary(1, 0) }}" }

# https://cert.ssi.gouv.fr/alerte/CERTFR-2018-ALE-009/
- name: TaskScheduler | Disable by ACL
  win_command: >
    cacls c:\Windows\Tasks
    /S:"D:PAI(D;OICI;DCLC;;;WD)(A;;0x1200ab;;;AU)(A;;FA;;;BA)(A;OICIIO;GA;;;BA)(A;;FA;;;SY)(A;OICIIO;GA;;;SY)(A;OICIIO;GA;;;CO)"
  when: harden_win_disable_taskscheduler_by_acl
