---

- name: Check if Nxlog archive already downloaded
  win_stat: path="{{ harden_win_temp_dir }}\\{{ harden_win_remotelogging_nxlog_url | basename }}"
  register: nxlogdl
- name: Download NXLog CE
  win_get_url:
    url: "{{ harden_win_remotelogging_nxlog_url }}"
    dest: "{{ harden_win_temp_dir }}\\{{ harden_win_remotelogging_nxlog_url | basename }}"
## FIXME! no checksum option
  when: not nxlogdl.stat.exists

- name: Install NXLog CE
  win_package:
    path: "{{ harden_win_temp_dir }}\\{{ harden_win_remotelogging_nxlog_url | basename }}"
    wait: true

- name: Configure NXLog CE
  win_template:
    src: "{{ item.s }}.j2"
    dest: "c:\\Program Files (x86)\\nxlog\\{{ item.d | default(item.s | basename) }}"
  with_items: "{{ harden_win_nxlog_conf | default([]) }}"

- name: Validate NXLog CE configuration
  win_command: >
    "c:\Program Files (x86)\nxlog\nxlog.exe" -c "c:\Program Files (x86)\nxlog\conf\nxlog.conf" -v
  changed_when: false

- name: Ensure nxlog service is enabled and started
  win_service:
    name: nxlog
    state: started
    start_mode: auto

## nxlog configuration or graylog sidecar?
## https://github.com/SMAPPER/NXLog-AutoConfig
## http://www.systeen.com/2016/05/12/install-graylog-2-0-centos-7-collect-windows-logs/
## https://github.com/Graylog2/collector-sidecar/releases
#"C:\Program Files (x86)\graylog\collector-sidecar\graylog-collector-sidecar.exe" -service install
#"C:\Program Files (x86)\graylog\collector-sidecar\graylog-collector-sidecar.exe" -service start
