---
## https://technet.microsoft.com/en-us/library/cc709644%28WS.10%29.aspx
## https://msdn.microsoft.com/en-us/library/windows/desktop/bb513638(v=vs.85).aspx
## https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/sosp153-glerum-web.pdf
## http://www.ten-inc.com/presentations/Websense_Crash_Whitepaper.PDF
## https://github.com/zredlined/drwatson/tree/master
## https://journeyintoir.blogspot.ca/2014/02/exploring-windows-error-reporting.html
## https://isc.sans.edu/forums/diary/Windows+Error+Reporting+DFIR+Benefits+and+Privacy+Concerns/22536/

- name: Configure Windows Error Reporting
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows\Windows Error Reporting
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: "{{ item.t }}"
  with_items:
## To enable or disable WER
    - { v: 'Disabled', d: '1', t: 'dword' }
# 1 Parameters only (default win7), 2 All Data (default vista)
    - { v: 'ConfigureArchive', d: '1', t: 'dword' }
# 1 Always Ask (default), 2 Parameters only, 3 Parameters and safe data, 4 All data
    - { v: 'Consent\DefaultConsent', d: '2', t: 'dword' }
#    - { v: 'CorporateWERDirectory', d: '', t: 'string' }
#    - { v: 'CorporateWERPortNumber', d: '', t: 'dword' }
#    - { v: 'CorporateWERServer', d: '', t: 'string' }
#    - { v: 'CorporateWERUseAuthentication', d: '', t: 'dword' }
#    - { v: 'CorporateWERUseSSL', d: '', t: 'dword' }
    - { v: 'DisableArchive', d: '0', t: 'dword' }
    - { v: 'DontShowUI', d: '1', t: 'dword' }
    - { v: 'DontSendAdditionalData', d: '1', t: 'dword' }
#    - { v: 'ExcludedApplications\[Application Name]', d: '', t: 'string' }
    - { v: 'ExcludedApplications\Keepass.exe', d: '', t: 'string' }
#    - { v: '', d: '', t: '' }
