---
# https://www.bleepingcomputer.com/news/security/why-everyone-should-disable-vssadmin-exe-now/

- block:
    - name: list state of shadow volumes
      win_command: "vssadmin.exe list volumes"
      changed_when: false
      register: vssvol
    - debug: var=vssvol
    - name: list state of shadowstorage
      win_command: "vssadmin.exe list shadowstorage"
      changed_when: false
      register: vssstor
      ignore_errors: true
    - debug: var=vssstor

    ## https://technet.microsoft.com/en-us/library/cc788051(v=ws.11).aspx
    ##  but return 'invalid command' in some cases??? only on server?
    ## 'add' option not available on win10
    - name: enable shadow copy for c
      win_command: "vssadmin.exe add shadowstorage /for=c: /on=c: /maxsize=15%"
      when:
        - '"Shadow Copy Storage volume: (C:)" not in vssstor.stdout'
        - ansible_distribution_major_version|int < 10
      ignore_errors: true

  when: ansible_distribution_major_version|int < 10

- name: ensure VSS service enabled
  win_service:
    name: "VSS"
    start_mode: auto
    state: started

## FIXME! UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 139: ordinal not in range(128)
## FIXME! win10: not idempotent
- name: schedule regular shadow copy
  win_scheduled_task:
    name: "VSS_Snapshot"
    description: "Take daily shadow copy for c"
    actions:
      - path: wmic.exe
        arguments: "/Namespace:\\root\\default Path SystemRestore Call CreateRestorePoint \"%DATE%\", 100, 7"
    triggers:
      - type: daily
        start_boundary: '2019-01-01T09:00:00'
    enable: yes
    state: present
    user: SYSTEM
  ignore_errors: true
#  when: ansible_distribution_major_version|int < 10

- name: Remove access permission vssadmin.exe
  win_acl:
    path: C:\Windows\system32\vssadmin.exe
    user: Everyone
    type: deny
    rights: ExecuteFile,Read,Write,Modify
    state: present
  when: ansible_distribution_major_version|int >= 10
