---
## Enable AppLocker in audit mode, Win Enterprise+
## https://technet.microsoft.com/en-us/library/dd759131(v=ws.11).aspx
## AppLocker Design Guide, Microsoft
## https://docs.microsoft.com/en-us/windows/device-security/applocker/applocker-policies-design-guide

## https://www.sixdub.net/?p=367
## https://dfir-blog.com/2016/01/03/protecting-windows-networks-applocker/
## http://www.scip.ch/en/?labs.20150507
## https://www.sysadmins.lv/blog-en/powershell-50-and-applocker-when-security-doesnt-mean-security.aspx
## block: {{ harden_win_temp_dir }}, C:\ProgramData, Recycle Bin
## block for non-admin users: Powershell+ddl? Deny: %SYSTEM32%\Windows\PowerShell\*

## https://insights.sei.cmu.edu/cert/2016/06/bypassing-application-whitelisting.html
## http://www.howtogeek.com/howto/8739/restrict-users-to-run-only-specified-programs-in-windows-7/
## https://www.bleepingcomputer.com/tutorials/create-an-application-whitelist-policy-in-windows/
## https://www.asd.gov.au/publications/protect/Hardening_Win7_SP1.pdf       13. list of path to whitelist
## Applocker to block program from
##  %USERPROFILE%, %ALLUSERSPROFILE%, %PUBLIC%, %OSDRIVE%\Users\*, %APPDATA%
##  %TEMP%, Recycler
##  %ProgramData%, %OSDRIVE%\Program Files\Common Files\Microsoft Shared\VBA\*
## https://github.com/MHaggis/hunt-detect-prevent/blob/master/Prevention/applocker.md
## https://github.com/MHaggis/hunt-detect-prevent/blob/master/Prevention/Applocker/applocker.xml
## https://github.com/iadgov/AppLocker-Guidance/tree/master/AppLocker%20Starter%20Policy
## https://www.sans.org/reading-room/whitepapers/Whitelists/finding-evil-whitelist-35832
## https://helgeklein.com/blog/2012/08/applocker-solutions-to-common-problems/  UAC=NoAppLocker group
## https://hinchley.net/articles/an-approach-for-managing-microsoft-applocker-policies/
## https://mssec.wordpress.com/2015/10/22/applocker-bypass-checker/

## powershell downgrade
## C:\WINDOWS\assembly\GAC_MSIL\System.Management.Automation
## C:\WINDOWS\assembly\NativeImages_v2.0.50727_64 or v2.0.*

- name: upload applocker policy
  win_template:
    src: "{{ harden_win_applocker_policy }}.j2"
    dest: "{{ harden_win_temp_dir }}\\{{ harden_win_applocker_policy }}"

- name: Configure Applocker policy
  win_shell: "Set-AppLockerPolicy -XMLPolicy {{ harden_win_temp_dir }}\\{{ harden_win_applocker_policy }}"

- name: Check current Applocker policy
  win_shell: Get-AppLockerPolicy -Local -Xml
  register: policy
  changed_when: false
- debug: var=policy.stdout_lines


- name: Non-domain | check if scheduled task to start AppIdSvc
  win_shell: schtasks /query /tn "AppIdSvc-start"
  changed_when: false
  register: schtask1
  failed_when: '"ERROR: The system cannot find the file specified." in schtask1.stdout'
  ignore_errors: true

## win_scheduled_task does not support onstart option
- name: Non-domain | ensure Application Identity service started
  win_shell: schtasks /create /tn "AppIdSvc-start" /tr "sc start AppIdSvc" /sc onstart /RU SYSTEM
  when: schtask1.failed

- name: Ensure Application Identity service started
  win_service:
    name: AppIdSvc
    state: started
