---

## http://la.trendmicro.com/media/misc/understanding-wmi-malware-research-paper-en.pdf
## https://files.sans.org/summit/Digital_Forensics_and_Incident_Response_Summit_2015/PDFs/TheresSomethingAboutWMIDevonKerr.pdf
## https://ics-cert.us-cert.gov/sites/default/files/documents/WMI_for_Detection_and_Response_S508C.pdf
## FIXME! cover root\subscription, root\default

## https://www.fireeye.com/blog/threat-research/2016/08/wmi_vs_wmi_monitor.html
## FIXME! no checksum option
- name: check if WMI_Monitor archive is present
  win_stat: path="{{ harden_win_temp_dir }}\\WMIMonitor.ps1"
  register: wmimondl
- name: Download WMI_Monitor
  win_get_url:
    url: https://raw.githubusercontent.com/realparisi/WMI_Monitor/master/WMIMonitor.ps1
    dest: "{{ harden_win_temp_dir }}\\WMIMonitor.ps1"
  when: not wmimondl.stat.exists

- name: Run WMIMonitor
  win_shell: "\"{{ harden_win_temp_dir }}\\WMIMonitor.ps1\""
  register: wmiout
  ignore_errors: true

- debug: var=wmiout
