---

# Review evt/log files to 100-500M + corresponding GPO
# https://dfirblog.wordpress.com/2015/10/11/protecting-windows-networks-essential-logging/
# https://logrhythm.com/fr/blog/powershell-command-line-logging/
# https://malwarearchaeology.squarespace.com/cheat-sheets/
# https://support.microsoft.com/en-us/kb/957662
# https://technet.microsoft.com/en-us/library/cc748849.aspx
# http://lifeofageekadmin.com/changing-windows-20032008-eventlog-size/
## https://msdn.microsoft.com/en-us/library/windows/desktop/aa363648(v=vs.85).aspx
## https://support.microsoft.com/en-ca/kb/957662
## alternative:     wevtutil sl <LogName> /ms:<MaxSizeInBytes>
## PS C:\> get-eventlog -list

- name: Base Event Log size review
  win_regedit:
    key: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item }}"
    value: MaxSize
    datatype: dword
    data: "{{ harden_win_eventlogs_maxsize }}"
  with_items:
    - Application
    - Security
    - System
    - Setup
    - Windows PowerShell

- name: Base Event Log retention review
  win_regedit:
    key: "HKLM:\\SYSTEM\\CurrentControlSet\\Services\\EventLog\\{{ item }}"
    value: Retention
    datatype: dword
    data: "{{ harden_win_logging_retention }}"
  with_items:
    - Application
    - Security
    - System
    - Setup
    - Windows PowerShell

- name: WINEVT Channels Event Log Enabled
  win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: Enabled
    datatype: dword
    data: 1
  with_items: "{{ harden_win_winevt_channels }}"

- name: WINEVT Channels Event Log size review
  win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: MaxSize
    datatype: dword
    data: "{{ harden_win_eventlogs_maxsize }}"
  with_items: "{{ harden_win_winevt_channels }}"

- name: WINEVT Channels Event Log retention review
  win_regedit:
    key: "HKLM:\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WINEVT\\Channels\\{{ item }}"
    value: Retention
    datatype: dword
    data: "{{ harden_win_logging_retention }}"
  with_items: "{{ harden_win_winevt_channels }}"
