---

- name: Pre-Win server 2012 Mimikatz Protection - UseLogonCredential
  win_regedit:
    key: HKLM:\System\CurrentControlSet\Control\SecurityProviders\WDigest
    value: UseLogonCredential
    data: 0
    datatype: dword

- name: Pre-Win server 2012 Mimikatz Protection - Negotiate
  win_regedit:
    key: HKLM:\System\CurrentControlSet\Control\SecurityProviders\WDigest
    value: Negotiate
    data: 0
    datatype: dword

## default: 0
- name: enabled User Account Control - Admin Approval Mode for the built-in Administrator account
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    value: FilterAdministratorToken
    data: 1
    datatype: dword

## default: does not exist
- name: Ensure Local admininistrators are filtered against Pass-The-Hash
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
    value: LocalAccountTokenFilterPolicy
    data: 0
    datatype: dword
  when: harden_win_mimikatz_LocalAccountTokenFilterPolicy0

- name: Enable LSA protection - RunAsPPL
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\LSA
    value: RunAsPPL
    data: 1
    datatype: dword
  when: harden_win_mimikatz_RunAsPPL
