---

- include: windows-logging-registry.yml
#- include: windows-logging-wevtutil.yml

## http://windowsitpro.com/networking/q-how-can-i-disable-netbios-over-tcpip-windows-server-core-installations
## https://technet.microsoft.com/en-us/library/cc775874%28v=ws.10%29.aspx
## https://technet.microsoft.com/en-us/library/ee692589.aspx
## https://www.4armed.com/blog/llmnr-nbtns-poisoning-using-responder/
## https://www.surecloud.com/newsletter/local-network-vulnerabilities-llmnr-and-nbt-ns-poisoning
## https://support.microsoft.com/en-us/help/313314/how-to-disable-netbios-over-tcp-ip-by-using-dhcp-server-options
- name: Disable Windows Link-Local Multicast Name Resolution (LLMNR)
  win_regedit:
    key: HKLM:\Software\Policies\Microsoft\Windows NT\DNSClient
    value: EnableMulticast
    data: 0
    datatype: dword


- name: Windows Netbios Name Service state with wmic
  win_command: "wmic /interactive:off nicconfig where TcpipNetbiosOptions={{ item }}"
  with_items:
    - 0
    - 1
  register: nbtstate
  changed_when: false
  ignore_errors: true
- block:
    - name: Disable Windows Netbios Name Service (NBT-NS)
##  win_regedit:
##  key: HKLM:\SYSTEM\CurrentControlSet\services\NetBT\Parameters\Interfaces\xxxGUIDxxx
##    value: NetbiosOptions
##    data: 2
## FIXME! doesn't seem to work
#  win_command: 'powershell -Command "set-ItemProperty HKLM:SYSTEMCurrentControlSetservicesNetBTParametersInterfacestcpip* -Name NetbiosOptions -Value 2"'
### This one is working fine
      win_command: "wmic /interactive:off nicconfig where TcpipNetbiosOptions={{ item }} call SetTcpipNetbios 2"
      with_items:
        - 0
        - 1
  when: nbtstate.results[0].stdout != "\r\r\n\r\r\n" and nbtstate.results[1].stdout != "\r\r\n\r\r\n"

## http://news.softpedia.com/news/how-to-prevent-zip-files-from-executing-malicious-javascript-behind-your-back-503226.shtml
## https://labsblog.f-secure.com/2016/04/19/how-to-disable-windows-script-host/
- name: disable Windows Script Host (1)
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
    value: Enabled
    data: 0
    datatype: dword
- name: disable Windows Script Host (2)
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
    value: IgnoreUserSettings
    data: 1
    datatype: dword
## not sure about this one?
#- name: Enable SAFER -  Software Restrictions Policies block scripts
#  win_regedit:
#    key: HKLM:\SOFTWARE\Microsoft\Windows Script Host\Settings
#    value: UseWinSAFER
#    data: 0

## https://bluesoul.me/2016/05/12/use-gpo-to-change-the-default-behavior-of-potentially-malicious-file-extensions/
## HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\
## \HKEY_CLASSES_ROOT\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts
## Partially covered if Windows Script Host is disabled
## FIXME! NOK
- name: disable suspicious executabled file extensions (HKCU)
  win_regedit:
#    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta
    key: "HKCU:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.{{ item }}"
#    key: "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\FileExts\\.{{ item }}"    ## NOK
#    key: "HKLM:\\Software\\Exts\\.{{ item }}"    ## NOK
    value: "(Default)"
    datatype: string
    data: "%windir%\\system32\\notepad.exe"
  with_items: "{{ harden_win_suspicious_ext }}"

## Note: HKCR only applies if HKCU doesn't exist. better enforcing with GPO
- name: disable javascript execution by Windows Script Host (HKCR)
  win_regedit:
#    key: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\FileExts\.hta
    key: "{{ item }}"
    data: "%windir%\\system32\\notepad.exe %1"
  with_items:
    - "HKCR:\\htafile\\shell\\open\\command"
    - "HKCR:\\VBSFile\\shell\\open\\command"
    - "HKCR:\\JSFile\\shell\\open\\command"
    - "HKCR:\\scriptletfile\\shell\\open\\command"  ## default

## https://www.stigviewer.com/stig/windows_8_8.1/2014-06-27/finding/V-43239
- name: Enable Cmdline in Audit Process creation
  win_regedit:
    key: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit
    value: ProcessCreationIncludeCmdLine_Enabled
    data: 1
    datatype: dword

## https://blogs.technet.microsoft.com/fdcc/2011/01/24/alwaysinstallelevated-is-equivalent-to-granting-administrative-rights/
## https://msdn.microsoft.com/en-us/library/windows/desktop/aa367561(v=vs.85).aspx
- name: Ensure Msiexec only executes with current user privileges
  win_regedit:
    key: HKLM:\Software\Policies\Microsoft\Windows\Installer
    value: AlwaysInstallElevated
    data: 0
    datatype: dword

- include: wpad-disable.yml
  when: harden_windows_disable_wpad is defined and harden_windows_disable_wpad

- name: Disable CMD
  win_regedit:
    key: HKCU:\Software\Policies\Microsoft\Windows\System
    value: DisableCMD
    datatype: dword
    data: 1
  when: harden_windows_disable_cmd

## https://onedrive.live.com/view.aspx?resid=A352EBC5934F0254!3316&ithint=file%2cpptx&app=PowerPoint
## https://support.microsoft.com/en-us/help/2871997/microsoft-security-advisory-update-to-improve-credentials-protection-and-management-may-13,-2014
- name: Win7/KB2871997 | trigger the clearing of any credentials of logged off users after 30 seconds
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa
    value: TokenLeakDetectDelaySecs
    datatype: dword
    data: 30

- include: windows-mimikatz.yml

## https://technet.microsoft.com/en-us/library/cc960646.aspx
- name: Strong Windows NTLMv2 Authentication Enabled; Weak LM/NTLM Disabled
  win_regedit:
    key: HKLM:\System\CurrentControlSet\Control\Lsa
    value: LmCompatibilityLevel
    datatype: dword
    data: 5

## https://technet.microsoft.com/en-us/library/dn408187(v=ws.11).aspx
## https://adsecurity.org/?p=3299, EventID 6065,3066
- name: Audit LSA plugins and drivers
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\LSASS.exe
    value: AuditLevel
    datatype: dword
    data: 8

## check also templates/win7-computer-security.inf
- name: Network security - Minimum session security for NTLM SSP based clients
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    value: NtlmMinClientSec
    datatype: dword
    data: 537395248

- name: Network security - Minimum session security for NTLM SSP based servers
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\Lsa\MSV1_0
    value: NtlmMinServerSec
    datatype: dword
    data: 537395248

- name: Windows Remote Desktop Configured to Always Prompt for Password
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    value: fPromptForPassword
    datatype: dword
    data: 1

- name: Strong Encryption for Windows Remote Desktop Required
  win_regedit:
    key: HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\Terminal Services
    value: MinEncryptionLevel
    datatype: dword
    data: 3

## http://www.antalyatasarim.com/registry/sources/detail-1235.htm
- name: Disable UPnP broadcasts
  win_regedit:
    key: HKLM:\SOFTWARE\Microsoft\DirectPlayNATHelp\DPNHUPnP
    value: UPnPMode
    datatype: dword
    data: 2

## https://www.stigviewer.com/stig/windows_8_8.1/2014-06-27/finding/V-3338
## https://technet.microsoft.com/en-us/library/jj852166(v=ws.11).aspx
## https://technet.microsoft.com/en-us/library/dd349805(v=ws.10).aspx#BKMK_44
## https://technet.microsoft.com/en-us/library/cc957461.aspx
- name: Ensure no anonymous access to named pipes
  win_regedit:
    key: HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters
    value: "{{ item.v }}"
    datatype: "{{ item.t }}"
    data: "{{ item.d }}"
    state: "{{ item.s }}"
  with_items:
    - { v: NullSessionPipes, t: multistring, d: '', s: absent  }
    - { v: RestrictNullSessAccess, t: dword, d: 1, s: present }

- name: Limit number of cached logon accounts
  win_regedit:
    key: HKLM:\Software\Microsoft\Windows NT\Current Version\Winlogon
    value: "cachedlogonscount"
    datatype: dword
    data: "{{ harden_win_cachedlogonscount }}"

## http://resources.infosecinstitute.com/windows-systems-artifacts-digital-forensics-part-iii-prefetch-files/
## http://www.forensicswiki.org/wiki/Prefetch
- name: Limit number of cached logon accounts
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management\PrefetchParameters
    value: "{{ item }}"
    datatype: dword
    data: 3
  with_items:
    - EnablePrefetcher
    - EnableSuperfetch

## https://technet.microsoft.com/en-us/library/cc959914.aspx
- name: Ensure last access times for NTFS partitions is enabled
  win_regedit:
    key: HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
    value: "NtfsDisableLastAccessUpdate"
    datatype: dword
    data: 0
