---
## https://www.microsoft.com/en-us/download/details.aspx?id=53337 Readiness Tool
## https://blogs.technet.microsoft.com/ash/2016/03/02/windows-10-device-guard-and-credential-guard-demystified/
## https://www.petri.com/windows-10-enterprise-feature-credential-guard
## https://github.com/iadgov/Secure-Host-Baseline/tree/master/Credential%20Guard
## WARNING! Not compatible with Windows Active Directory Domain Controller! (DC)

- name: Enable Credential Guard with DISM
  win_command: "{{ item }}"
  with_items:
    - dism /enable-feature /FeatureName:Microsoft-Hyper-V-Hypervisor
    - dism /enable-feature /FeatureName:IsolatedUserMode

# Group Policy: Computer configuration\Administrative Templates\System\Device Guard: Trun on virtualization based security = Enabled
