---
## https://docs.ansible.com/ansible/win_firewall_rule_module.html
## https://support.microsoft.com/en-gb/kb/947709
## Multiple issues
## https://github.com/ansible/ansible-modules-extras/issues/2882        win_firewall_rule fails if rule already exists
## https://github.com/ansible/ansible/issues/18807                      win_firewall_rule fails when locale isn't English
## https://github.com/ansible/ansible/issues/18861                      After commit 9392943 win_firewall_rules rules default to services only
## FIXME! Rules not visible in management console or
##      HKLM:\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\<profilename>
##      HKLM\Software\Policies\Microsoft\WindowsFirewall\<Profilename>  (if set by gpo)

## https://technet.microsoft.com/en-us/library/ee693371(v=exchg.80).aspx
## not sure if apply to Win10?
- name: Ensure Firewall is enabled for all profile
  win_regedit:
    key: "HKLM:\\Software\\Policies\\Microsoft\\WindowsFirewall\\{{ item }}"
    value: EnableFirewall
    data: 1
    datatype: dword
  with_items:
    - DomainProfile
    - StandardProfile
    - PublicProfile

## FIXME! win_firewall_rule not idempotent

- name: Firewall | allow svchost dns and ntp requests out
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-allow-outgoing-svchost-{{ item }}"
    program: "%SystemRoot%\\System32\\svchost.exe"
    enable: yes
    state: present
    localport: any
    remoteport: "{{ item }}"
    action: allow
    direction: Out
  with_items:
    - 53
    - 123
## FIXME! not idempotent. https://github.com/ansible/ansible-modules-extras/pull/2654 related?
  ignore_errors: true

- name: Firewall | block outgoing program
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-block-outgoing-{{ item | basename }}"
    program: "{{ item }}"
    enable: yes
    state: present
    localport: any
    action: block
    direction: Out
#    protocol: TCP
    profile: Public
  with_items: "{{ harden_win_fw_program_blocked_out_public }}"
#  ignore_errors: true

- name: Firewall | allow outgoing program
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-allow-outgoing-{{ item | basename }}"
    enable: yes
    state: present
    action: allow
    direction: Out
    profile: Public
  with_items: "{{ harden_win_fw_program_allowed_out_public }}"
#  ignore_errors: true

- name: Firewall | allow outgoing web program
  include: "windows-firewall-unit.yml action=allow direction=Out profile=public ports={{ harden_win_fw_web_ports }}"
  with_items: "{{ harden_win_fw_program_allowed_web_out_public }}"

- name: Firewall | block outgoing ports
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-block-outgoing-{{ item }}"
    enable: yes
    state: present
    localport: any
    remoteport: "{{ item }}"
    action: block
    direction: Out
#    protocol: TCP
    profile: Public
  with_items: "{{ harden_win_fw_ports_blocked_out_public }}"
#  ignore_errors: true

- name: Firewall | allow outgoing ports
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-allow-outgoing-{{ item }}"
    enable: yes
    state: present
    localport: any
    remoteport: "{{ item }}"
    action: allow
    direction: Out
    profile: Public
  with_items: "{{ harden_win_fw_ports_allowed_out_public }}"
#  ignore_errors: true

## FIXME! 'Unexpected failure during module execution.', 'AttributeError: 'int' object has no attribute 'rfind''
- name: Firewall | block incoming ports
  win_firewall_rule:
    name: "{{ harden_win_fw_prefix }}-block-incoming-{{ item }}"
    enable: yes
    state: present
    localport: "{{ item }}"
    remoteport: any
    action: block
    direction: In
#    protocol: TCP
    profile: Public
  with_items: "{{ harden_win_fw_ports_blocked_in_public }}"


- debug: var=harden_win_fw_rules_disable
- name: Firewall | disable rules
  win_firewall_rule:
    name: "{{ item }}"
    direction: Out
    action: allow
    state: present
    enable: no
  with_items: "{{ harden_win_fw_rules_disable }}"
#  ignore_errors: true


## FIXME! default rule
## does not seem supported by ansible: http://docs.ansible.com/ansible/win_firewall_rule_module.html
## rule order(block, after allow, after default): https://technet.microsoft.com/en-us/library/cc755191(v=ws.10).aspx
#- name: Last Firewall rule (~default)
#  win_firewall_rule:
#    name: "{{ harden_win_fw_prefix }}-default-rule-{{ harden_win_fw_default_action }}"
#    direction: "{{ item }}"
#    enable: yes
#    action: "{{ harden_win_fw_default_action }}"
#    state: present
#  with_items:
#    - in
#    - out

- name: Firewall reconfigure logging
  win_command: "{{ item }}"
  with_items:
#    - netsh advfirewall set currentprofile logging maxfilesize 4096
## 'Log file size must be between 1 and 32767.'
    - netsh advfirewall set currentprofile logging maxfilesize 32767
    - netsh advfirewall set currentprofile logging droppedconnections enable
    - netsh advfirewall set currentprofile logging allowedconnections enable

