---

- name: Disable Windows Administrative shares - registry
  win_regedit:
    key: "{{ item.k }}"
    value: "{{ item.v }}"
    data: "{{ item.d }}"
    datatype: dword
  with_items:
    - { k: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters', v: 'AutoShareWks', d: 0 }
    - { k: 'HKLM:\SYSTEM\CurrentControlSet\Services\LanManServer\Parameters', v: 'AutoShareServer', d: 0 }
    - { k: 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa', v: 'restrictanonymous', d: 1 }

# OK https://ci.appveyor.com/project/juju4/ansible-harden-windows/builds/25835253
# NOK https://ci.appveyor.com/project/juju4/ansible-harden-windows/builds/26122112/job/lbkffjihylphl9cq#L5430
- name: Disable Windows Administrative shares - current session
  win_share:
    name: "{{ item }}"
    state: absent
#  win_command: "net share {{ item }} /delete"
  with_items:
    - "admin$"
    - "c$"
    - "d$"
    - "e$"
  ignore_errors: true
